### ISSUE TITLE
If there are too many filenames on the command line, a logging error appears

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/normalize-filename#41]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/handlers.py", line 899, in emit
    self.socket.send(msg)
OSError: [Errno 40] Message too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/handlers.py", line 903, in emit
    self.socket.send(msg)
OSError: [Errno 40] Message too long
Call stack:
  File "/x/normalize-filename/normalize-filename", line 446, in <module>
    main(sys.argv, sysLogHandler, sysErrHandler)
  File "/x/normalize-filename/normalize-filename", line 151, in main
    logger.debug("Arguments are: " + str(args))

**Comment by andrewferrier** [comment]
Seems to be related to this issue: http://bugs.python.org/issue11907

**Comment by andrewferrier** [comment]
Use a different type of formatter to limit syslog lengths: file:///Users/ferriera/Documents/Sites/python-3.4.3-docs-html/howto/logging-cookbook.html#formatting-styles

**Comment by andrewferrier** [comment]
See http://stackoverflow.com/a/16799284/27641 for fix.
