### ISSUE TITLE
Normalizing a file called X • Y.pdf doesn't work, using the Finder service only

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/normalize-filename#46]
* OS X 10.10.4
* The file is renamed but there is a failure in the workfow.

**Comment by andrewferrier** [comment]
Appears to be a unicode issue:

```
Traceback (most recent call last):
  File ".../Library/Services/normalize-filename-finder.workflow/Contents/normalize-filename", line 446, in <module>
    main(sys.argv, sysLogHandler, sysErrHandler)
  File ".../Library/Services/normalize-filename-finder.workflow/Contents/normalize-filename", line 173, in main
    process_filename(filename, args)
  File ".../Library/Services/normalize-filename-finder.workflow/Contents/normalize-filename", line 289, in process_filename
    shiftfile(args, original_filename, filename)
  File ".../Library/Services/normalize-filename-finder.workflow/Contents/normalize-filename", line 348, in shiftfile
    log_file.write("# " + dt_now + ": moving " + source + " to " + target + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 48: ordinal not in range(128)
```
