### ISSUE TITLE
Tests are failing on Travis CI

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/normalize-filename#49]
May be related to #44.

```
Traceback (most recent call last):
  File "/home/travis/build/andrewferrier/normalize-filename/tests/Subprocess/test_Subprocess_Basic.py", line 196, in test_basicdateprefix_interactive_edit
    child.expect("filename\? ")
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pexpect/expect.py", line 102, in expect_loop
    return self.eof(e)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pexpect/expect.py", line 49, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x2abfc857ec18>
command: /home/travis/build/andrewferrier/normalize-filename/normalize-filename
args: ['/home/travis/build/andrewferrier/normalize-filename/normalize-filename', '/tmp/tmpqa7wonya/blah.txt', '--interactive', '--no-undo-log-file']
searcher: None
buffer (last 100 chars): b''
before (last 100 chars): b'xsocket\r\n    self.socket.connect(address)\r\nFileNotFoundError: [Errno 2] No such file or directory\r\ne'
```

At a guess, this may be because `/dev/log` doesn't exist. May need to check for that and disable logging.

**Comment by andrewferrier** [comment]
Appears that this was failing because of opening an "invalid" syslog socket inside Pexpect tests. Still not quite clear why, but syslog support no longer needed anyway (see #45), so removed.
